# Generated by Django 5.2.5 on 2025-12-10 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cita_metodo_pago_alter_cita_id_alter_clinica_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='anticipo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='cita',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cita',
            name='monto_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('comprobante', models.CharField(blank=True, max_length=100)),
                ('monto_facturado', models.DecimalField(decimal_places=2, max_digits=8)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('otro', 'Otro')], max_length=20)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('restante', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='core.cita')),
            ],
        ),
    ]
