# Generated by Django 5.2.5 on 2025-12-10 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cita_anticipo_cita_descuento_porcentaje_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha_pago', '-id']},
        ),
        migrations.AlterField(
            model_name='cita',
            name='anticipo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma de todos los abonos registrados.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='cita',
            name='monto_final',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total de la cita después de descuentos.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='pago',
            name='cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.cita'),
        ),
    ]
