# Generated by Django 5.2.5 on 2026-02-12 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pago_options_alter_cita_anticipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('colaborador', 'Colaborador'), ('recepcion', 'Recepcionista')], default='colaborador', max_length=20)),
                ('titulo', models.CharField(blank=True, max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('foto', models.CharField(blank=True, max_length=255)),
                ('clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to='core.clinica')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
