# Generated by Django 5.2.5 on 2026-02-12 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_paciente_fecha_nac_alter_paciente_genero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('rol', models.CharField(choices=[('fisioterapeuta', 'Fisioterapeuta'), ('nutriologo', 'Nutriólogo'), ('dentista', 'Dentista'), ('recepcion', 'Recepción'), ('admin', 'Administrador')], default='fisioterapeuta', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
