# Generated by Django 5.2.5 on 2026-02-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_staffprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofile',
            old_name='created_at',
            new_name='creado',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='staff/'),
        ),
    ]
