# Generated by Django 5.2.5 on 2026-02-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_created_at_staffprofile_creado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estado_tratamiento',
            field=models.CharField(choices=[('en_tratamiento', 'En tratamiento'), ('alta', 'Dado de alta')], default='en_tratamiento', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_alta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
