# Generated by Django 5.2.5 on 2026-03-09 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_servicio_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('categoria', models.CharField(choices=[('Insumo', 'Insumo'), ('Medicamento', 'Medicamento')], default='Insumo', max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('minimo', models.PositiveIntegerField(default=0)),
                ('notas', models.CharField(blank=True, default='', max_length=250)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='core.clinica')),
            ],
            options={
                'ordering': ['nombre', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], max_length=10)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('motivo', models.CharField(blank=True, default='', max_length=200)),
                ('before', models.PositiveIntegerField(default=0)),
                ('after', models.PositiveIntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_insumos', to=settings.AUTH_USER_MODEL)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.insumo')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
