# Generated by Django 5.2.5 on 2026-03-09 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_insumo_movimientoinsumo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpedienteClinico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacion', models.CharField(blank=True, default='', max_length=120)),
                ('direccion', models.TextField(blank=True, default='')),
                ('heredo_familiares', models.TextField(blank=True, default='')),
                ('antecedentes', models.JSONField(blank=True, default=dict)),
                ('habitos', models.JSONField(blank=True, default=dict)),
                ('documentos', models.JSONField(blank=True, default=dict)),
                ('notas_generales', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SesionClinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo_consulta', models.CharField(blank=True, default='', max_length=200)),
                ('intensidad_dolor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('zonas_dolor', models.JSONField(blank=True, default=list)),
                ('notas', models.TextField(blank=True, default='')),
                ('exploracion', models.TextField(blank=True, default='')),
                ('diagnostico', models.TextField(blank=True, default='')),
                ('tratamiento_realizado', models.TextField(blank=True, default='')),
                ('recomendaciones', models.TextField(blank=True, default='')),
                ('estado_sesion', models.CharField(blank=True, choices=[('estable', 'Estable'), ('mejorando', 'Mejorando'), ('igual', 'Sin cambios'), ('empeorando', 'Empeorando'), ('alta', 'Alta')], default='', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['nombres', 'apellido_pat', 'apellido_mat', '-id']},
        ),
        migrations.AlterField(
            model_name='paciente',
            name='molestia',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='notas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['clinica', 'telefono'], name='core_pacien_clinica_c894c1_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['clinica', 'correo'], name='core_pacien_clinica_c3b01f_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['estado_tratamiento'], name='core_pacien_estado__1a2c1d_idx'),
        ),
        migrations.AddField(
            model_name='expedienteclinico',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expediente', to='core.paciente'),
        ),
        migrations.AddField(
            model_name='sesionclinica',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_clinicas', to='core.cita'),
        ),
        migrations.AddField(
            model_name='sesionclinica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_clinicas', to='core.paciente'),
        ),
        migrations.AddField(
            model_name='sesionclinica',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_clinicas_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sesionclinica',
            index=models.Index(fields=['paciente', 'fecha'], name='core_sesion_pacient_756c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='sesionclinica',
            index=models.Index(fields=['profesional', 'fecha'], name='core_sesion_profesi_272c53_idx'),
        ),
    ]
