# Generated by Django 5.2.5 on 2026-03-12 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_expedienteclinico_sesionclinica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueohorario',
            name='agenda_tipo',
            field=models.CharField(choices=[('general', 'General'), ('acondicionamiento', 'Acondicionamiento'), ('terapia', 'Terapia')], db_index=True, default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='cita',
            name='agenda_tipo',
            field=models.CharField(choices=[('general', 'General'), ('acondicionamiento', 'Acondicionamiento'), ('terapia', 'Terapia')], db_index=True, default='general', max_length=30),
        ),
        migrations.AddIndex(
            model_name='bloqueohorario',
            index=models.Index(fields=['agenda_tipo', 'fecha'], name='core_bloque_agenda__173541_idx'),
        ),
        migrations.AddIndex(
            model_name='bloqueohorario',
            index=models.Index(fields=['agenda_tipo', 'profesional', 'fecha'], name='core_bloque_agenda__6fd413_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['agenda_tipo', 'fecha'], name='core_cita_agenda__0f403f_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['agenda_tipo', 'profesional', 'fecha'], name='core_cita_agenda__58084f_idx'),
        ),
    ]
