# Generated by Django 5.2.5 on 2026-03-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_bloqueohorario_agenda_tipo_cita_agenda_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='color_agenda',
            field=models.CharField(blank=True, default='#d47b06', max_length=20),
        ),
    ]
