# Generated by Django 5.2.5 on 2026-03-20 16:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_staffprofile_color_agenda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaClinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='', max_length=180)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('tipo_archivo', models.CharField(choices=[('imagen', 'Imagen'), ('pdf', 'PDF'), ('otro', 'Otro')], default='otro', max_length=10)),
                ('archivo', models.FileField(upload_to='evidencias_clinicas/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf'])])),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotaClinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('subjetivo', models.TextField(blank=True, default='')),
                ('objetivo', models.TextField(blank=True, default='')),
                ('analisis', models.TextField(blank=True, default='')),
                ('plan', models.TextField(blank=True, default='')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RecetaMedica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('diagnostico', models.TextField(blank=True, default='')),
                ('indicaciones_generales', models.TextField(blank=True, default='')),
                ('medicamentos', models.JSONField(blank=True, default=list)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='facturacion_codigo_postal',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='paciente',
            name='facturacion_correo',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='paciente',
            name='facturacion_razon_social',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='paciente',
            name='facturacion_regimen_fiscal',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='paciente',
            name='facturacion_rfc',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
        migrations.AddField(
            model_name='paciente',
            name='facturacion_uso_cfdi',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='paciente',
            name='requiere_factura',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['clinica', 'apellido_pat', 'apellido_mat'], name='core_pacien_clinica_08f6d6_idx'),
        ),
        migrations.AddField(
            model_name='evidenciaclinica',
            name='cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_clinicas', to='core.cita'),
        ),
        migrations.AddField(
            model_name='evidenciaclinica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_clinicas', to='core.paciente'),
        ),
        migrations.AddField(
            model_name='evidenciaclinica',
            name='sesion_clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_clinicas', to='core.sesionclinica'),
        ),
        migrations.AddField(
            model_name='evidenciaclinica',
            name='subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_clinicas_subidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notaclinica',
            name='cita',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nota_clinica', to='core.cita'),
        ),
        migrations.AddField(
            model_name='notaclinica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_clinicas', to='core.paciente'),
        ),
        migrations.AddField(
            model_name='notaclinica',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_clinicas_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notaclinica',
            name='sesion_clinica',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nota_clinica', to='core.sesionclinica'),
        ),
        migrations.AddField(
            model_name='recetamedica',
            name='cita',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receta_medica', to='core.cita'),
        ),
        migrations.AddField(
            model_name='recetamedica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_medicas', to='core.paciente'),
        ),
        migrations.AddField(
            model_name='recetamedica',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas_medicas_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='evidenciaclinica',
            index=models.Index(fields=['paciente', 'cita'], name='core_eviden_pacient_f1a3ac_idx'),
        ),
        migrations.AddIndex(
            model_name='notaclinica',
            index=models.Index(fields=['paciente', 'fecha'], name='core_notacl_pacient_f2c55a_idx'),
        ),
    ]
