# Generated by Django 5.2.5 on 2026-03-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_evidenciaclinica_notaclinica_recetamedica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaclinica',
            name='contenido_nom004',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notaclinica',
            name='tipo_nota',
            field=models.CharField(choices=[('historia_clinica', 'Historia clínica'), ('evolucion', 'Nota de evolución'), ('interconsulta', 'Nota de interconsulta'), ('referencia_traslado', 'Nota de referencia / traslado')], default='evolucion', max_length=30),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='cedula_profesional',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
