# Generated by Django 5.2.5 on 2026-03-30 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_notaclinica_contenido_nom004_notaclinica_tipo_nota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaclinica',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='recetamedica',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
