# Generated by Django 5.2.5 on 2026-04-01 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_notaclinica_fecha_alter_recetamedica_fecha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-creado', '-id']},
        ),
        migrations.AddField(
            model_name='comentario',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentario',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_recibidos', to='core.servicio'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='tipo_objetivo',
            field=models.CharField(choices=[('profesional', 'Profesional'), ('servicio', 'Servicio')], db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='aprobado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='calificacion',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='descripcion',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='nombre_completo',
            field=models.CharField(blank=True, default='Paciente anónimo', max_length=100),
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['aprobado', 'creado'], name='core_coment_aprobad_b623bf_idx'),
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['tipo_objetivo', 'profesional'], name='core_coment_tipo_ob_43b443_idx'),
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['tipo_objetivo', 'servicio'], name='core_coment_tipo_ob_2ad7ed_idx'),
        ),
    ]
