# Generated by Django 5.2.5 on 2026-04-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_comentario_options_comentario_profesional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('fisioterapeuta', 'Fisioterapeuta'), ('aux_fisioterapia', 'Auxiliar de fisioterapia'), ('recepcionista', 'Recepcionista')], default='recepcionista', max_length=30),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='rol',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('fisioterapeuta', 'Fisioterapeuta'), ('aux_fisioterapia', 'Auxiliar de fisioterapia'), ('recepcionista', 'Recepcionista')], default='recepcionista', max_length=30),
        ),
    ]
