# Generated by Django 5.2.5 on 2026-04-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_perfilusuario_rol_alter_staffprofile_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='alerta_stock_bajo_enviada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='insumo',
            name='alerta_stock_bajo_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
