# Generated by Django 5.2.5 on 2026-05-24 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_insumo_alerta_stock_bajo_enviada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='objetivo_publico',
            field=models.CharField(blank=True, choices=[('rehabilitacion_general', 'Rehabilitación general'), ('acondicionamiento_general', 'Acondicionamiento general')], db_index=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='evidenciaclinica',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_clinicas', to='core.cita'),
        ),
        migrations.AlterField(
            model_name='notaclinica',
            name='cita',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nota_clinica', to='core.cita'),
        ),
        migrations.AlterField(
            model_name='recetamedica',
            name='cita',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receta_medica', to='core.cita'),
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['tipo_objetivo', 'objetivo_publico'], name='core_coment_tipo_ob_b4ef9a_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenciaclinica',
            index=models.Index(fields=['paciente', 'creado'], name='core_eviden_pacient_2f03d0_idx'),
        ),
        migrations.AddIndex(
            model_name='recetamedica',
            index=models.Index(fields=['paciente', 'fecha'], name='core_receta_pacient_5076bf_idx'),
        ),
    ]
